framr:
  cordapps:

  initConnections:

  cordappModule:
    cordappRegistryType: INMEMORY

  nodeRPCModule:
    rpcManagerType: INMEMORY

  nodeDBModule:
    dbConfigurationManagerType: INMEMORY


management:
  endpoints:
    web:
      exposure:
        include: "*"