framr:
    cordapps:
        - "demo-cordapp-contracts-0.1.jar"
        - "demo-cordapp-workflows-0.1.jar"

    initConnections:
        - rpcHost: "corda-node-a"
          rpcPort: 10003
          rpcUsername: "user1"
          rpcPassword: "test"
          dbUrl: "jdbc:postgresql://database/node"
          dbDriver: "org.postgresql.Driver"
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
          dbUsername: "postgres"
          dbPassword: "password"

    cordappModule:
      cordappRegistryType: INMEMORY
  
    nodeRPCModule:
      rpcManagerType: INMEMORY
  
    nodeDBModule:
      dbConfigurationManagerType: INMEMORY


management:
  endpoints:
    web:
      exposure:
        include: "*"